### ISSUE TITLE
Out-of-scope exception

### ISSUE THREAD

**Issue by RF0** [enonic/app-status#1]
Enonic XP 6.10.3

I get this "out of scope" error message when I open the admin tool

com.enonic.xp.resource.ResourceProblemException: unexpected url: /admin/tool/com.enonic.app.status/system-info/draft/_/error/400?message=URI+out+of+scope (java.lang.RuntimeException)

**Comment by jsi** [comment]
I do not get the error when I run locally, but on enonic.com, the error is present.  VHost problem?

**Comment by alansemenov** [comment]
@RF0 @jsi I fixed the error but vhost should still be configured so that /status url works on the host server. It works locally for us because of this setting in default vhost config:
```
mapping.test.host = localhost
mapping.test.source = /
mapping.test.target = /
mapping.test.userStore = system
```

On Enonic prod and QA it's not configured, so it won't work even after my fix. 
It can be easily tested like this:
http://localhost:8080/status - works
http://enonic.com/status - doesn't work
http://qa.enonic.com/status - doesn't work

I think we should set it up on enonic servers (both prod and QA) to be available at
<host>/admin/status

I will release the new version of app with the fix next week.

**Comment by jsi** [comment]
I can fix the vhost.  We can test it out on QA with the new version.

What we currently have on enonic is this:

```
mapping.admin.host = qa.enonic.com
mapping.admin.source = /admin
mapping.admin.target = /admin
mapping.admin.userStore = system
```

Are you saying we need something like this? : 
```
mapping.admin.host = qa.enonic.com
mapping.admin.source = /admin/status
mapping.admin.target = /status
mapping.admin.userStore = system
```

If so, we should also document it with the app.

**Comment by alansemenov** [comment]
I believe so, yes. I have now updated the app on QA with the new version, so now it's just a matter of properly configuring vhost.

**Comment by alansemenov** [comment]
Just an add-on - new mapping related to status url should be in addition to current mapping, not instead!

**Comment by jsi** [comment]
So, Alan have fixed the "Out of scope" exception now.  He will release version 1.0.1 now.

But, it is also important that the vhost is configured correctly.  On enonic.com, we needed this vhost config to make it work:

```
mapping.status.host = enonic.com
mapping.status.source = /status
mapping.status.target = /status
mapping.status.userStore = system
```

**Comment by sigdestad** [comment]
Mapping the status service directly to enonic.com/status is a no-go. Actually, the way this app works is a no-go. It should not use the /status endpoint, but have it's own service do this job. Reason is we are not able to secure the /status endpoint like we can with services. Also, in future versions of XP /status will be moved to a separate port

**Comment by jsi** [comment]
Ok, @sigdestad .  I have documented this challenge.  Now we need to rework the app for version 2.
